authors:
  josh_ring:
    name: Josh Ring
    description: Contributor
    avatar: https://github.com/joshring.png
    url: https://github.com/joshring

  lerno:
    name: Christoffer Lernö
    description: Creator
    avatar: https://github.com/lerno.png
    url: https://github.com/lerno